# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:

    runs-on: ubuntu-latest
    steps:
#       - uses: actions/checkout@v2
#         with: 
#           path: './'
#           token: ${{secrets.COMMIT}}
#       - name: code commit
#         run: echo "`jq '.volumes[0].efsVolumeConfiguration.fileSystemId="sgsdgshfdhfghfghfghfghfg"' ./.github/workflows/test.json `" > ./.github/workflows/test.json
#       - uses: stefanzweifel/git-auto-commit-action@v4
#         with:
#           commit_message: 'Add the EFS volume generated application'
#           file_pattern: ./.github/workflows/test.json 
#           push_options: '--force'
#           tagging_message: 'v1.0.0'
#           cwd: './'  
#           token: ${{secrets.COMMIT}}
      - name: Take time to Mongodb_Script_Upload
        run: |
          ls
#          cd devops/local/docker
#          mongo ${{ needs.Deploy_backend.outputs.public_ip }}:27017/efscode_7462 -u admin -p password --authenticationDatabase admin < mongo.js
          

